name: docker deploy

on:
  push:
    branches:
      - initial

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
        continue-on-error: true  # Remove this once you're sure secrets work

#      - name: ⚙Set up QEMU
#        uses: docker/setup-qemu-action@v3
#
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/backend:latest

      - name:  Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.TRAIN_SERVER_IP }}
          username: ${{ secrets.TRAIN_SERVER_USER }}
          key: ${{ secrets.TRAIN_SERVER_SSH_KEY }}
          script: |
            echo " Starting Deployment..."
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GHCR_PAT }}
            docker pull ghcr.io/${{ github.repository_owner }}/backend:latest
            echo "Docker image pulled successfully"
            docker run ${{ github.repository_owner }}/backend:latest
